### ISSUE TITLE
npm test, throws error on node v0.10.25

### ISSUE THREAD

**Issue by ghost** [akiran/react-test-examples#1]
I have node - v0.10.25 and npm - 1.3.10 on my machine.
I git cloned, ran npm install and then npm test.
It throws error as,

``` javascript
WARN [watcher]: Pattern "/home/sk/ws/react-test-examples/test/**/*.js" does not match any file.
WARN [preprocess]: Can not load "webpack"!
  TypeError: Object [object Object] has no method 'refreshFiles'
    at Plugin.notifyKarmaAboutChanges (/home/sk/ws/react-test-examples/node_modules/karma-webpack/index.js:108:15)
    at Plugin.<anonymous> (/home/sk/ws/react-test-examples/node_modules/karma-webpack/index.js:72:9)
    at Tapable.applyPlugins (/home/sk/ws/react-test-examples/node_modules/webpack/node_modules/tapable/lib/Tapable.js:26:37)
    at Watching._done (/home/sk/ws/react-test-examples/node_modules/webpack/lib/Compiler.js:78:17)
    at Watching.<anonymous> (/home/sk/ws/react-test-examples/node_modules/webpack/lib/Compiler.js:61:18)
    at Tapable.emitRecords (/home/sk/ws/react-test-examples/node_modules/webpack/lib/Compiler.js:281:37)
    at Watching.<anonymous> (/home/sk/ws/react-test-examples/node_modules/webpack/lib/Compiler.js:58:19)
    at /home/sk/ws/react-test-examples/node_modules/webpack/lib/Compiler.js:274:11
    at Tapable.applyPluginsAsync (/home/sk/ws/react-test-examples/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
    at Tapable.afterEmit (/home/sk/ws/react-test-examples/node_modules/webpack/lib/Compiler.js:271:8)
INFO [karma]: Karma v0.12.37 server started at http://localhost:9876/
INFO [launcher]: Starting browser PhantomJS
INFO [PhantomJS 1.9.8 (Linux 0.0.0)]: Connected on socket mHv9kt6D0UfwpfMMaXYs with id 30069652
PhantomJS 1.9.8 (Linux 0.0.0) ERROR
  SyntaxError: Parse error
  at /home/sk/ws/react-test-examples/test/01-hello.test.jsx:9
```

**Comment by akiran** [comment]
I package version issue.

I fixed it. Can you try now

**Comment by ghost** [comment]
it works......
